Description: >
    Server Infrastructure / UdagramTestEnvironment /

Parameters:
    # NOTE: All IP ranges should be written in CIDR notation (#.#.#.#/#)
    EnvironmentName:
        Description: Environment name to be prefixed to resource names.
        Type: String
    JumpBoxAllowedCidr:
        Description: The IP address allowed to SSH into a Jump Box EC2 instance running within a public subnet allowing access to servers in a private subnet.
        Type: String
    WebServerImageId:
        Description: Fully qualified ami image id.
        Type: String

Resources:
### SECURITY GROUPS ###
    JumpBoxSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Jump Box / For accessing servers on private subnet. Only allow Port 22 for SSH on ingress. Allow all egress for updating.
            VpcId:
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-VPCID"
            SecurityGroupIngress:
              - IpProtocol: tcp
                FromPort: 22
                ToPort: 22
                CidrIp: !Ref JumpBoxAllowedCidr
            SecurityGroupEgress:
              - IpProtocol: tcp
                FromPort: 22
                ToPort: 22
                CidrIp: !Ref JumpBoxAllowedCidr
              - IpProtocol: tcp
                FromPort: 0
                ToPort: 65535
                CidrIp: 0.0.0.0/0

    LBSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Load Balancer / Allow all TCP on port 80 (HTTP) for ingress and egress.
            VpcId:
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-VPCID"
            SecurityGroupIngress:
              - IpProtocol: tcp
                FromPort: 80
                ToPort: 80
                CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
              - IpProtocol: tcp
                FromPort: 80
                ToPort: 80
                CidrIp: 0.0.0.0/0

    WebServerSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow HTTP and SSH on Network only, Any Outbound traffic.
            VpcId:
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-VPCID"
            SecurityGroupIngress:
              - IpProtocol: tcp
                FromPort: 80
                ToPort: 80
                CidrIp: 10.0.0.0/24
              - IpProtocol: tcp
                FromPort: 22
                ToPort: 22
                CidrIp: 10.0.0.0/24
            SecurityGroupEgress:
              - IpProtocol: tcp
                FromPort: 0
                ToPort: 65535
                CidrIp: 0.0.0.0/0

### JUMP BOX INSTANCE ###
    JumpBoxInstance:
        Type: AWS::EC2::Instance
        Properties:
            InstanceType: t2.micro
            ImageId: ami-0ce21b51cb31a48b8 # Amazon Linux 2 AMI 64-Bit x86
            SubnetId:
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-PUB1-SN"
            KeyName: jumpbox-key
            SecurityGroupIds:
              - Ref: JumpBoxSecGroup
            IamInstanceProfile: Udagram-EC2-S3-ReadOnly
            InstanceInitiatedShutdownBehavior: "stop"
            BlockDeviceMappings:
              - DeviceName: "/dev/sdk"
                Ebs:
                    VolumeSize: '10'
            Tags:
              - Key: Name
                Value: JumpBox
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash
                    yum update -y
                    cd /home/ec2-user
                    aws s3 cp s3://udagram-test-environment/keys/private-server-devops-key.pem private-server-devops-key.pem
                    chmod 400 private-server-devops-key.pem
                    chown ec2-user private-server-devops-key.pem
